hindi_pure = [
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>लाल</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>नीला</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>हरा</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>लाल</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "नीला",
      "लाल",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "लाल",
      "नीला",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:green'>नीला</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "हरा",
      "लाल",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:red'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "लाल",
      "हरा",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "हरा",
      "नीला",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 1,
    block: "hindi pure",
    stim: "<p style='color:blue'>हरा</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "नीला",
      "हरा",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
];