# ---- Packages ----
library(lme4)
library(simr)

set.seed(20251007)

# ---- Design & assumptions ----
# N participants, trials per participant, fully within-subject 2x2:
N_subj   <- 30
trials_pp <- 240                # 60 per cell in a 2x2 within-subject design
cells     <- 4
trials_per_cell <- trials_pp / cells

# Factors
# UrWord_mixed: 0 = baseline, 1 = "mixed" (or Urdu-word-mixed, per your spec)
# incongruent:  0 = congruent, 1 = incongruent
subj <- factor(rep(seq_len(N_subj), each = trials_pp))
UrWord_mixed <- factor(rep(rep(c(0,1), each = trials_per_cell), times = N_subj * 2))
incongruent  <- factor(rep(rep(c(0,1), each = trials_per_cell*2), times = N_subj))

# Base dataframe (response will be generated by simr)
d <- data.frame(subj, UrWord_mixed, incongruent)

# ---- Fixed effects on the log-RT scale ----
# Assumed baseline mean RT (ms) in the reference cell (UrWord_mixed=0, congruent=0):
mu_ms <- 700

# Classic Stroop interference ~ 90 ms (main effect of incongruency):
stroop_ms <- 90

# Target interaction size (extra incongruency cost when UrWord_mixed==1):
int_ms_40 <- 40   # main power target
int_ms_20 <- 20   # smaller effect to test difficulty

# We assume no main effect of UrWord_mixed on congruent trials for simulation:
mixed_main_ms <- 0

# Convert those to coefficients on the log scale.
# Coding is treatment contrasts: intercept = log mean in reference cell (0,0).
b0          <- log(mu_ms)
b_incong    <- log(mu_ms + stroop_ms) - log(mu_ms)                       # log(790) - log(700)
b_mixed     <- log(mu_ms + mixed_main_ms) - log(mu_ms)                   # here 0
b_int_40    <- log(mu_ms + stroop_ms + int_ms_40) - log(mu_ms + stroop_ms) # log(830)-log(790)
b_int_20    <- log(mu_ms + stroop_ms + int_ms_20) - log(mu_ms + stroop_ms) # log(810)-log(790)

c(b0 = b0, b_mixed = b_mixed, b_incong = b_incong, b_int_40 = b_int_40, b_int_20 = b_int_20)
# (Optional) sanity check: exp(b0) ~ 700; exp(b0+b_incong) ~ 790; etc.

# ---- Random effects & residual SD (log-RT) ----
sd_subj_intercept <- 0.15   # participant-level intercept SD on log-RT
sd_residual       <- 0.20   # residual SD on log-RT

# ---- Build a model object with simr::makeLmer ----
# Important: term names depend on factor names/levels; for two-level factors with default contrasts,
# coefficients will be "UrWord_mixed1", "incongruent1", and their interaction.
fixefs_40 <- c("(Intercept)" = b0,
               "UrWord_mixed1" = b_mixed,
               "incongruent1"  = b_incong,
               "UrWord_mixed1:incongruent1" = b_int_40)

m40 <- makeLmer(
  formula = logRT ~ UrWord_mixed*incongruent + (1|subj),
  fixef   = fixefs_40,
  VarCorr = list(subj = sd_subj_intercept^2),
  sigma   = sd_residual,
  data    = d
)

# Quick check: names(fixef(m40))

# ---- Power for the ~40 ms interaction ----
# Test the UrWord_mixed:incongruent interaction with a t-test on the fixed effect
pwr_40 <- powerSim(
  m40,
  test  = fixed("UrWord_mixed1:incongruent1", method = "t"),
  nsim  = 1000,   # increase if you want tighter MC error
  seed  = 20251007
)
print(pwr_40)

# ---- Power for a smaller ~20 ms interaction (harder to detect) ----
fixef(m40)["UrWord_mixed1:incongruent1"] <- b_int_20
pwr_20 <- powerSim(
  m40,
  test  = fixed("UrWord_mixed1:incongruent1", method = "t"),
  nsim  = 1000,
  seed  = 20251007
)
print(pwr_20)

# ---- (Optional) Reportable summaries ----
# You can capture MC 95% CIs from powerSim objects:
summary(pwr_40)
summary(pwr_20)

# ---- (Optional) Power curve vs N participants ----
# Keep trials per participant fixed (240); vary N to visualize sensitivity.
# NOTE: This uses the 20 ms effect currently set in m40; set it back to b_int_40 if desired.
# Set back to 40 ms if you want that curve:
# fixef(m40)["UrWord_mixed1:incongruent1"] <- b_int_40
pc <- powerCurve(
  m40,
  along = "subj",   # step the number of subjects
  nsim  = 400,      # fewer sims to keep it quick; increase for publication
  seed  = 20251007
)
print(pc)
plot(pc)
