urdu_pure= [
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>لال</p>",
    stim_eng: "red",
    congruency: "congruent",
    colour: "red",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>نیلا</p>",
    stim_eng: "blue",
    congruency: "congruent",
    colour: "blue",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>ہرا</p>",
    stim_eng: "green",
    congruency: "congruent",
    colour: "green",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>لال</p>",
    stim_eng: "red",
    congruency: "incongruent",
    colour: "green",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "نیلا",
      "لال",
    ],
    options_roman: [
      "nila",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "red",
    options: [
      "لال",
      "نیلا",
    ],
    options_roman: [
      "laal",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:green'>نیلا</p>",
    stim_eng: "blue",
    congruency: "incongruent",
    colour: "green",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "ہرا",
      "لال",
    ],
    options_roman: [
      "haraa",
      "laal",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:red'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "red",
    options: [
      "لال",
      "ہرا",
    ],
    options_roman: [
      "laal",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "ہرا",
      "نیلا",
    ],
    options_roman: [
      "haraa",
      "nila",
    ],
    correct_answer: 1,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
  {
    block_num: 2,
    block: "urdu pure",
    stim: "<p style='color:blue'>ہرا</p>",
    stim_eng: "green",
    congruency: "incongruent",
    colour: "blue",
    options: [
      "نیلا",
      "ہرا",
    ],
    options_roman: [
      "nila",
      "haraa",
    ],
    correct_answer: 0,
  },
];